version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
